apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  SESSION_SECRET: Sms4aDNKazlIM2tKSGs5SDNqa0g5a0pIM2tqSDlrSkgza2pIOWtqSDNrSjlIM2tqSA==
  ACCESS_TOKEN_SECRET: Sms4aDNKazlIM2tKSGs5SDNqa0g5a0pIM2tqSDlrSkgza2pIOWtqSDNrSjlIM2tqSA==
  REFRESH_TOKEN_SECRET: Sms4aDNKazlIM2tKSGs5SDNqa0g5a0pIM2tqSDlrSkgza2pIOWtqSDNrSjlIM2tqSA==
  MONGO_URI: bW9uZ29kYjovL2FkbWluOlN0cjBuZ1BAc3MhQDEwLjEyOC4wLjUwOjI3MDE3L2NzMzA4ZGI/YXV0aFNvdXJjZT1hZG1pbg==
