apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <yourdockeraccountname>/vegan-eats-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "/backend"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000 # Choose an available port above 30000
  type: NodePort  # Use LoadBalancer for cloud environments, or ClusterIP for internal
