version: '3.8'

services:
  backend:
    build:
      context: ../backend/Vegan-Eats
    container_name: vegan-eats-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/veganeats
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: veganeats-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: ../frontend/308_frontend
    container_name: vegan-eats-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
